NAME=ao

PATH_DIRECTORY_CERO=../cer0
PATH_DIRECTORY_CERO_LIBRARY=${PATH_DIRECTORY_CERO}/library
PATH_DIRECTORY_INCLUDE=include
PATH_DIRECTORY_OBJECTS=objects
PATH_DIRECTORY_OUTPUT=output
PATH_DIRECTORY_SOURCES=sources

PATH_FILE_OBJECT_CERO=${PATH_DIRECTORY_CERO_LIBRARY}/cer0.o
PATH_FILE_OUTPUT=${PATH_DIRECTORY_OUTPUT}/${NAME}

FILES_SOURCES=${wildcard ${PATH_DIRECTORY_SOURCES}/*.c}
FILES_OBJECTS=${patsubst ${PATH_DIRECTORY_SOURCES}/%.c,${PATH_DIRECTORY_OBJECTS}/%.o,${FILES_SOURCES}}

C_OPTS=-O3 -I${PATH_DIRECTORY_INCLUDE} -I../cer0/include
C_OPTS_EXECUTABLE=-framework CoreAudio

CC=clang

${PATH_FILE_OUTPUT}: ${FILES_OBJECTS} ${PATH_DIRECTORY_OUTPUT}
	${CC} ${C_OPTS} ${C_OPTS_EXECUTABLE} ${FILES_OBJECTS} ${PATH_FILE_OBJECT_CERO} -o ${PATH_FILE_OUTPUT}

${PATH_DIRECTORY_OBJECTS}/%.o: ${PATH_DIRECTORY_SOURCES}/%.c ${PATH_DIRECTORY_OBJECTS}
	${CC} ${C_OPTS} -c $< -o $@

${PATH_DIRECTORY_OBJECTS}:
	mkdir ${PATH_DIRECTORY_OBJECTS}

${PATH_DIRECTORY_OUTPUT}:
	mkdir ${PATH_DIRECTORY_OUTPUT}

clean:
	-rm -r ${PATH_DIRECTORY_OBJECTS} 2> /dev/null
	-rm -r ${PATH_DIRECTORY_OUTPUT} 2> /dev/null

